"""
Django settings for data_aggregation project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv_if_exists() -> None:
    """
    簡易 .env ローダー（追加依存なし）
    - 形式: KEY=VALUE
    - 先頭/末尾の空白は除去
    - # から始まる行はコメントとして無視
    - 既に環境変数にあるKEYは上書きしない
    """

    # リポジトリの制約でドットファイルが作りにくい場合があるため、
    # `.env` だけでなく `env` も読む。
    for env_filename in (".env", "env"):
        env_path = BASE_DIR / env_filename
        if not env_path.exists():
            continue

        for raw_line in env_path.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value


_load_dotenv_if_exists()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9sh#su8y=ys88=#$=jy#()vowfcxty4(lzdf8wt7ru*-^&0o(5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashbords',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 既定は SQLite（リポジトリ同梱の db.sqlite3）にして、PostgreSQL は明示設定時のみ使用する。
# - まずは `python manage.py runserver` を確実に動かすため
# - PostgreSQL を使う場合は `env` / `.env` に POSTGRES_PASSWORD を設定する（env.example 参照）
# - もしくは強制的に PostgreSQL を使いたい場合は USE_POSTGRES=1 を設定する
USE_POSTGRES = os.getenv("USE_POSTGRES", "").strip().lower() in {"1", "true", "yes", "on"}
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "").strip()

if USE_POSTGRES:
    if not POSTGRES_PASSWORD:
        raise ImproperlyConfigured(
            "USE_POSTGRES=1 が設定されていますが POSTGRES_PASSWORD が未設定です。"
            "env/.env または環境変数で POSTGRES_PASSWORD を設定してください。"
        )
    DATABASES = {
        "default": {
            # PostgreSQL (psql)
            # 例: Windows PowerShell で環境変数を設定
            #   $env:POSTGRES_DB="data_aggregation"
            #   $env:POSTGRES_USER="postgres"
            #   $env:POSTGRES_PASSWORD="password"
            #   $env:POSTGRES_HOST="127.0.0.1"
            #   $env:POSTGRES_PORT="5432"
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "data_aggregation"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Auth
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
