# Generated by GPT to migrate opponent_deck_text -> opponent_deck_ref (OpponentDeck)

from django.db import migrations


def forwards(apps, schema_editor):
    Result = apps.get_model("dashbords", "Result")
    OpponentDeck = apps.get_model("dashbords", "OpponentDeck")

    for r in Result.objects.select_related("user").all():
        name = (getattr(r, "opponent_deck_text", "") or "").strip()
        if not name:
            continue
        od, _ = OpponentDeck.objects.get_or_create(user_id=r.user_id, name=name, defaults={"is_active": True})
        r.opponent_deck_ref_id = od.id
        r.save(update_fields=["opponent_deck_ref"])


class Migration(migrations.Migration):
    dependencies = [
        ("dashbords", "0007_remove_result_opponent_deck_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]


