# Generated by GPT to finalize opponent deck FK migration non-interactively

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashbords", "0008_migrate_opponent_deck_text_to_ref"),
    ]

    operations = [
        migrations.RenameField(
            model_name="result",
            old_name="opponent_deck_ref",
            new_name="opponent_deck",
        ),
        migrations.RemoveField(
            model_name="result",
            name="opponent_deck_text",
        ),
    ]


